Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-mat','Agregar Materia');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-mat','Modificar Materia');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-mat','Eliminar Materia');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-usu','Agregar Usuario');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-usu','Modificar Usuario');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-usu','Eliminar Usuario');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-pro','Agregar Proceso');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-pro','Modificar Proceso');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-pro','Eliminar Proceso');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-exp','Agregar Expediente');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-exp','Modificar Expediente');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-exp','Eliminar Expediente');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-abg','Agregar Abogado');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-abg','Modificar Abogado');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-abg','Eliminar Abogado');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-cli','Agregar Cliente');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-cli','Modificar Cliente');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-cli','Eliminar Cliente');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-act','Agregar Actuacion');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-act','Modificar Actuacion');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-act','Eliminar Actuacion');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-des','Agregar Despacho');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-des','Modificar Despacho');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-des','Eliminar Despacho');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-doc','Agregar Documento');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-doc','Modificar Documento');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-doc','Eliminar Documento');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-estEx','Agregar EstadoExpediente');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-estEx','Modificar EstadoExpediente');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-estEx','Eliminar EstadoExpediente');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-estExtInt','Agregar EstadoExternoInterno');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-estExtInt','Modificar EstadoExternoInterno');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-estExtInt','Eliminar EstadoExternoInterno');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-per','Agregar Persona');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-per','Modificar Persona');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-per','Eliminar Persona');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-tipAbg','Agregar Tipo Abogado');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-tipAbg','Modificar Tipo Abogado');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-tipAbg','Eliminar Tipo Abogado');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-tipAct','Agregar Tipo Actuacion');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-tipAct','Modificar Tipo Actuacion');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-tipAct','Eliminar Tipo Actuacion');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-tipCli','Agregar Tipo Cliente');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-tipCli','Modificar Tipo Cliente');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-tipCli','Eliminar Tipo Cliente');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-tipDem','Agregar Tipo Demanda');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-tipDem','Modificar Tipo Demanda');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-tipDem','Eliminar Tipo Demanda');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-tomo','Agregar Tomo');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-tomo','Modificar Tomo');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-tomo','Eliminar Tomo');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-caja','Agregar Caja');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-caja','Modificar Caja');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-caja','Eliminar Caja');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-factura','Agregar Factura');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-factura','Modificar Factura');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-factura','Eliminar Factura');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-ingEgre','Agregar IngresoEgreso');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-ingEgre','Modificar IngresoEgreso');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-ingEgre','Eliminar IngresoEgreso');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-servicio','Agregar Servicio');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-servicio','Modificar Servicio');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-servicio','Eliminar Servicio');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-tipoIngEgre','Agregar TipoIngresoEgreso');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-tipoIngEgre','Modificar TipoIngresoEgreso');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-tipoIngEgre','Eliminar TipoIngresoEgreso');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-empleado','Agregar Empleado');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-empleado','Modificar Empleado');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-empleado','Eliminar Empleado');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-movimiento','Agregar Movimiento');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-movimiento','Modificar Movimiento');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-movimiento','Eliminar Movimiento');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'agr-planilla','Agregar PlanillaSalario');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'mod-planilla','Modificar PlanillaSalario');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'eli-planilla','Eliminar PlanillaSalario');
Insert into permiso values(NEXTVAL('permiso_id_seq'),'completo','Permiso Completo');