INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'CORTE SUPREMA DE JUSTICIA','juez1');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'FUNCIONARIOS AUXILIARES AL PROCESO','juez2');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'Juzgado de Feria Civil y Comercial 2015','juez3');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE JUSTICIA LETRADA DEL 1° TURNO SRIA. 1','juez4');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE JUSTICIA LETRADA DEL 1° TURNO SRIA. 2','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE JUSTICIA LETRADA DEL 2° TURNO SRIA. 3','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE JUSTICIA LETRADA DEL 2° TURNO SRIA. 4','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE JUSTICIA LETRADA DEL 3° TURNO SRIA. 5','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE JUSTICIA LETRADA DEL 3° TURNO SRIA. 6','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE JUSTICIA LETRADA DEL 4° TURNO SRIA. 7','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE JUSTICIA LETRADA DEL 4° TURNO SRIA. 8','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE JUSTICIA LETRADA DEL 5° TURNO SRIA. 10','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE JUSTICIA LETRADA DEL 5° TURNO SRIA. 9','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE JUSTICIA LETRADA DEL 6° TURNO SRIA. 11','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE JUSTICIA LETRADA DEL 6° TURNO SRIA. 12','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LA NIÑEZ Y ADOLESCENCIA, CUARTO TURNO, Sria. 7','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LA NIÑEZ Y ADOLESCENCIA, CUARTO TURNO, Sria. 8','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LA NIÑEZ Y ADOLESCENCIA, PRIMER TURNO, Sria. 1','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LA NIÑEZ Y ADOLESCENCIA, PRIMER TURNO, Sria. 2','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LA NIÑEZ Y ADOLESCENCIA, QUINTO TURNO, Sria. 10','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LA NIÑEZ Y ADOLESCENCIA, QUINTO TURNO, Sria. 9','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LA NIÑEZ Y ADOLESCENCIA, SEGUNDO TURNO, Sria. 3','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LA NIÑEZ Y ADOLESCENCIA, SEGUNDO TURNO, Sria. 4','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LA NIÑEZ Y ADOLESCENCIA, SEXTO TURNO, Sria. 11','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LA NIÑEZ Y ADOLESCENCIA, SEXTO TURNO, Sria. 12','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LA NIÑEZ Y ADOLESCENCIA, TERCER TURNO, Sria. 5','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LA NIÑEZ Y ADOLESCENCIA, TERCER TURNO, Sria. 6','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LO LABORAL DE FERIA 2012','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LO LABORAL DEL CUARTO TURNO, Sria. 7','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LO LABORAL DEL CUARTO TURNO, Sria. 8','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LO LABORAL DEL PRIMER TURNO, Sria. 1','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LO LABORAL DEL PRIMER TURNO, Sria. 2','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LO LABORAL DEL QUINTO TURNO, Sria. 10','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LO LABORAL DEL QUINTO TURNO, Sria. 9','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LO LABORAL DEL SEGUNDO TURNO, Sria. 3','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LO LABORAL DEL SEGUNDO TURNO, Sria. 4','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LO LABORAL DEL SEXTO TURNO, Sria. 11','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LO LABORAL DEL SEXTO TURNO, Sria. 12','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LO LABORAL DEL TERCER TURNO, Sria. 5','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE LO LABORAL DEL TERCER TURNO, Sria. 6','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE LA CATEDRAL, 1º TURNO, SEC. Nº 1 ','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE LA CATEDRAL, 1º TURNO, SEC. Nº 2','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE LA CATEDRAL, 1º TURNO, SEC. Nº 3','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE LA CATEDRAL, 2º TURNO, SEC. Nº 3 ','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE LA CATEDRAL, 2º TURNO, SEC. Nº 4 ','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE LA ENCARNACIÓN, 1º TURNO, SEC. Nº 1','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE LA ENCARNACIÓN, 1º TURNO, SEC. Nº 2','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE LA ENCARNACIÓN, 2º TURNO, SEC. Nº 3','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE LA ENCARNACIÓN, 2º TURNO, SEC. Nº 4','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE LA RECOLETA, 1º TURNO, SEC. Nº 1','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE LA RECOLETA, 1º TURNO, SEC. Nº 2','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE SAN ROQUE, 1º TURNO, SEC. Nº 1','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE SAN ROQUE, 1º TURNO, SEC. Nº 2','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE SANTISIMA TRINIDAD, 1º  TURNO, SEC. Nº 1','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE SANTISIMA TRINIDAD, 1º  TURNO, SEC. Nº 2','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE SANTISIMA TRINIDAD, 2º  TURNO, SEC. Nº 3','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE SANTISIMA TRINIDAD, 2º TURNO, SEC. Nº 4','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE SANTISIMA TRINIDAD, 3er  TURNO, SEC. Nº 5','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE SANTISIMA TRINIDAD, 3er  TURNO, SEC. Nº 6','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE VILLA MORRA, 1º TURNO, SEC. Nº 1 ','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE VILLA MORRA, 1º TURNO, SEC. Nº 2','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE ZEBALLOS CUE, 1º TURNO, SEC. Nº 1','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PAZ DE ZEBALLOS CUE, 1º TURNO, SEC. Nº 2','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL CUARTO TURNO, Sria. 7','juez1');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL CUARTO TURNO, Sria. 8','juez2');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO CUARTO TURNO, Sria. 27','juez3');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO CUARTO TURNO, Sria.28','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO NOVENO TURNO, Sria.37','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO NOVENO TURNO, Sria.38','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO OCTAVO TURNO, Sria.35','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO OCTAVO TURNO, Sria.36','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO QUINTO TURNO, Sria. 29','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO QUINTO TURNO, Sria.30','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO SEPTIMO TURNO, Sria.33','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO SEPTIMO TURNO, Sria.34','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO SEXTO TURNO, Sria. 31','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO SEXTO TURNO, Sria.32','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO TERCER TURNO, Sria. 25','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO TERCER TURNO, Sria. 26','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO TURNO, Sria. 19 ','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DECIMO TURNO, Sria. 20','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DUODECIMO TURNO, Sria. 23','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL DUODECIMO TURNO, Sria. 24','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL NOVENO TURNO, Sria. 17','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL NOVENO TURNO, Sria. 18','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL OCTAVO TURNO, Sria. 15','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL OCTAVO TURNO, Sria. 16','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL PRIMER TURNO, Sria. 1','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL PRIMER TURNO, Sria. 2','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL QUINTO TURNO, Sria. 10','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL QUINTO TURNO, Sria. 9','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL SEGUNDO TURNO, Sria. 3','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL SEGUNDO TURNO, Sria. 4','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL SEPTIMO TURNO, Sria. 13','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL SEPTIMO TURNO, Sria. 14','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL SEXTO TURNO, Sria. 11','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL SEXTO TURNO, Sria. 12','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL TERCER TURNO, Sria. 5','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL TERCER TURNO, Sria. 6','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL UNDECIMO TURNO, Sria. 21','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL UNDECIMO TURNO, Sria. 22','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL VIGESIMO TURNO, Sria.39 ','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL Y COMERCIAL DEL VIGESIMO TURNO, Sria.40','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO EN LO CIVIL Y COMERCIAL 10° TURNO / ACTUARIO: NORMA CRISTALDO','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO EN LO CIVIL, COMERCIAL Y LABORAL ','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS EN DELITOS ECONOMICOS','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS NRO. 1','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS NRO. 10','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS NRO. 11','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS NRO. 12','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS NRO. 13','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS NRO. 2','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS NRO. 3','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS NRO. 4','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS NRO. 5','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS NRO. 6','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS NRO. 7','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS NRO. 8','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE GARANTIAS NRO. 9','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE LA ADOLESCENCIA, 1ER TURNO','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE LA ADOLESCENCIA, 2DO TURNO','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE LA ETAPA PREPARATORIA','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'JUZGADO PENAL DE LIQUIDACION DE CAUSAS MENORES INFRACTORES','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'PLENO DE LA CORTE SUPREMA DE JUSTICIA','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'REASIGNACION DE CAUSAS - INHIBICION/RECUSACION','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'SALA CIVIL','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'SALA PENAL','Gizela Gonzalez');
INSERT INTO despacho(id,descripcion,juez) VALUES(NEXTVAL('despacho_id_seq'),'SINDICATURA GENERAL DE QUIEBRAS','Gizela Gonzalez');
